# Generated by Django 4.1.7 on 2023-02-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='albumsongnumber',
            name='unique_songs_of_album',
        ),
        migrations.RenameField(
            model_name='albumsongnumber',
            old_name='song_title',
            new_name='song',
        ),
        migrations.AddConstraint(
            model_name='albumsongnumber',
            constraint=models.UniqueConstraint(fields=('song', 'album'), name='unique_songs_of_album'),
        ),
    ]
